### PR TITLE
[Enhancement] Toggle Main Aircraft Door

### PR DESCRIPTION
**Pull request by VCAmyPopple**
I have added the initial logic for door handling in C#.

I will add the door button visuals soon.

### CODE REVIEW

**Comment by VCAmyPopple** [comment]
New Assets have been added (however, they may need sharpening)

**Comment by VCAmyPopple** [comment]
Result:
image
image

**Comment by alex-johnson** [comment]
@VCAmyPopple Hey we had a similar idea! Check out my PR that accomplishes something similar. Would love if you could test it out.

**Review by metindikbas — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
